service: pattern-example
package:
    exclude:
        - .*
        - .**/**
        - aws/**
        - test/**
        - README.md
        - serverless.yml
        - package.json
        - package-lock.json
custom:
    logRetentionInDays: 1
    cors:
        origin: '*'
        allowCredentials: false
        headers:
            - Content-Type
            - Authorization
            - x-api-key
    serverless-offline:
        httpPort: 9000
        stage: local
        prefix: ${self:service}
        region: us-east-2
        noAuth: true
        noPrependStageInUrl: true
provider:
    name: aws
    runtime: nodejs14.x
    versionFunctions: false
    endpointType: regional
    profile: ${opt:profile, 'local'}
    stage: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-2'}
    stackName: ${self:provider.stackTags.name}
    apiName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: ${self:provider.stage}-${self:provider.region}-alc-examples
    stackTags:
        name: ${self:provider.stage}-${self:service}
        service: ${self:service}
        environment: ${self:provider.stage}
        managed-by: serverless
resources:
    - ${file(./aws/resources/apigateway.yml)}
functions:
    v1-apigateway-handler:
        name: ${self:provider.stackTags.name}-v1-apigateway-handler
        handler: api/_router.route
        description: example router for pattern routing with alc
        memorySize: 256
        timeout: 30
        events:
            - http:
                path: /
                method: ANY
                cors: ${self:custom.cors}
            - http:
                path: /{proxy+}
                method: ANY
                cors: ${self:custom.cors}
plugins:
    - serverless-plugin-bind-deployment-id
    - serverless-plugin-log-retention
    - serverless-deployment-bucket
    - serverless-offline
